### PR TITLE
Spw download enabled develop

### PR DESCRIPTION
**Pull request by will-moore**
These are the additional commits to #3351 backported to develop.

To test:

 - Download of SPW data should be disabled by default, both when a single well is selected and when multiple wells are selected (batch annotate panel). Download of non-SPW images should still be working.
 - After configuration and restart of web: ``` $ bin/omero config set omero.web.plate_download.enabled True ```
Now, download should be enabled for single or multiple selected wells, BUT OME-TIFF export should still be disabled for all SPW data.
 - Finally, check that OME-TIFF is still enabled for non-SPW data.

NB: Need to switch the error for archived_files/download from 500 to 404 when the specified images have no archived files.

--rebased-from #3351.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#735](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/735/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/735/consoleText) for more details.
Possible conflicts:
  - PR #3392 will-moore 'Download menus web'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html

**Comment by will-moore** [comment]
@pwalczysko asking about this got me thinking that maybe we shouldn't disable individual Image export as PNG / JPEG etc for selected wells, Just don't allow original file (Plate) download?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#736](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/736/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/736/consoleText) for more details.
Possible conflicts:
  - PR #3392 will-moore 'Download menus web'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#737](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/737/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/737/consoleText) for more details.
Possible conflicts:
  - PR #3392 will-moore 'Download menus web'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#738](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/738/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/738/consoleText) for more details.
Possible conflicts:
  - PR #3392 will-moore 'Download menus web'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#739](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/739/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/739/consoleText) for more details.
Possible conflicts:
  - PR #3392 will-moore 'Download menus web'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#740](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/740/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/740/consoleText) for more details.
Possible conflicts:
  - PR #3392 will-moore 'Download menus web'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#741](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/741/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/741/consoleText) for more details.
Possible conflicts:
  - PR #3392 will-moore 'Download menus web'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#742](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/742/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/742/consoleText) for more details.
Possible conflicts:
  - PR #3392 will-moore 'Download menus web'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-5.1-merge-push#743](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/743/). See the [console output](http://ci.openmicroscopy.org/job/OME-5.1-merge-push/743/consoleText) for more details.
Possible conflicts:
  - PR #3392 will-moore 'Download menus web'
    - components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/annotations/includes/toolbar.html

**Comment by will-moore** [comment]
Sorry - didn't get around to fixing this PR till now. Just merged origin/develop so hopefully merge conflicts are fixed now. @sbesson, could you remove the "exclude" label? Thanks

**Comment by sbesson** [comment]
Can you backport the 5 last commits on the original PR? Or are these handled somewhere else?

**Comment by will-moore** [comment]
@sbesson After cherry-picking those last 5 commits, and trying to run the test:
```
cd OmeroWeb
./setup.py test -t test/integration/test_download.py
...
==================================================================================== test session starts =====================================================================================
platform darwin -- Python 2.7.8 -- py-1.4.26 -- pytest-2.6.4
collected 0 items / 1 errors 

=========================================================================================== ERRORS ===========================================================================================
_____________________________________________________________________ ERROR collecting test/integration/test_download.py _____________________________________________________________________
test/integration/test_download.py:30: in <module>
    import test.integration.library as lib
E   ImportError: No module named integration.library
================================================================================== 1 error in 1.43 seconds ===================================================================================
```
Am I missing something else from 5.0?

**Comment by sbesson** [comment]
@will-moore no this is completely `develop` specific (divergence introduced by https://github.com/openmicroscopy/openmicroscopy/pull/3296/files). Replacing

```
import library as lib
```

by

```
import library as lib
```

should work

**Comment by will-moore** [comment]
Thanks, now I'm getting:
```
        o = lib.ITest()
>       o.setup_method(None)
E       AttributeError: 'ITest' object has no attribute 'setup_method'
```
Sorry, I should investigate myself - but if you know what's wrong off the top of your head..?

**Comment by sbesson** [comment]
Yes this is the result of another `develop` only PR https://github.com/openmicroscopy/openmicroscopy/pull/3318. Using `setup_class` and `teardown_class` should work - see omeroweb test files modified by the PR linked above.

**Comment by will-moore** [comment]
Thanks @sbesson. All working now...
```
===== 2 passed in 41.69 seconds ====
```

**Comment by sbesson** [comment]
```
./components/tools/OmeroWeb/omeroweb/webgateway/views.py:2066:80: E501 line too long (91 > 79 characters)
./components/tools/OmeroWeb/omeroweb/webgateway/views.py:2071:80: E501 line too long (87 > 79 characters)
./components/tools/OmeroWeb/omeroweb/webgateway/views.py:2072:80: E501 line too long (84 > 79 characters)
```

**Comment by will-moore** [comment]
@sbesson Do we need your last commit from #3351? https://github.com/will-moore/openmicroscopy/commit/be13fa875334e0ae372781baea025869b7f21d30

**Comment by sbesson** [comment]
@will-moore: no this should already be in `develop`. This had been cherry-picked to `dev_5_0` to let your integration tests pass there.

**Comment by sbesson** [comment]
From the integration tests POV https://ci.openmicroscopy.org/job/OMERO-5.1-merge-integration-web/260/testReport/test.integration.test_download/ looks good.

**Comment by dominikl** [comment]
Functionality works like described. If code has been checked by @sbesson before, good to merge.
