### PR TITLE
Blitz getattr with units

### PR DESCRIPTION
**Pull request by will-moore**
In 5.1 the API for methods that return units is unchanged from 5.0. E.g.
```
# omero.model.pixelsI - this works in 5.0 and 5.1
pixels.getPhysicalSizeX().getValue()
```
However, in the Blitz Gateway this is now broken
```
# pixelsWrapper
pixels.getPhysicalSizeX().getValue()
AttributeError: 'UnitsLength' object has no attribute 'getValue'
```
We get this error in Make_Movie script (although this used to work until recently)?
This PR updates Blitz Gateway ``` __getattr__ ``` to handle units and includes a test:

```
$ cd OmeroPy
$ ./setup.py test -t test/integration/gatewaytest/test_image.py -k testUnitsGetValue
```

Check that tests are passing at https://ci.openmicroscopy.org/view/Failing/job/OMERO-5.1-merge-integration/ and Make_Movie script works.

--no-rebase

### CODE REVIEW

**Comment by joshmoore** [comment]
@will-moore : I'd assume this is related to https://github.com/openmicroscopy/openmicroscopy/pull/3530#issuecomment-76287162

**Comment by will-moore** [comment]
@joshmoore Yes - both are fixes for the same issue, but no idea what caused it.

**Comment by ximenesuk** [comment]
Test passes locally, make movie works, code looks okay.
