### PR TITLE
disable testPopulateMetadataPlate

### PR DESCRIPTION
**Pull request by will-moore**
This turns off the breaking parts of testPopulateMetadataPlate, which is broken due to https://github.com/openmicroscopy/openmicroscopy/commit/d3a0b36208b84 

https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-python/384/testReport/junit/OmeroPy.test.integration.metadata.test_populate/TestPopulateMetadata/testPopulateMetadataPlate/

cc @joshmoore @manics

### CODE REVIEW

**Comment by jburel** [comment]
test failures: `TestTables.testTableAddData 'Table' object has no attribute 'colnames'`

**Comment by will-moore** [comment]
Test passing now: https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-python/388/testReport/junit/OmeroPy.test.integration.metadata.test_populate/TestPopulateMetadata/testPopulateMetadataPlate/

**Comment by joshmoore** [comment]
https://ci.openmicroscopy.org/view/Failing/job/OMERO-DEV-merge-integration-python/388/testReport/junit/OmeroPy.test.integration.metadata.test_populate/TestPopulateMetadata/testPopulateMetadataPlate/

Thanks, @will-moore. I'll file a card for the upcoming unification that's needed for populate_metadata.
